import { config } from 'dotenv';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load environment variables from monorepo root for local development
// In production (Vercel), env vars are injected from the dashboard
if (process.env.WEATHERB_VERIFY !== '1' && process.env.WEATHERB_ENV_FILE !== 'none')
  config({ path: resolve(__dirname, '../../.env') });

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Repository instructions are maintained by the project, not generated by Next.
  agentRules: false,
  reactStrictMode: true,
  transpilePackages: ['@weatherb/shared'],
  images: {
    qualities: [75, 85],
  },
};

export default nextConfig;
